services:
  hello:
    build:
      context: .
      dockerfile: hello/Dockerfile
    container_name: hello
    ports:
      - "50051:50051"
    environment:
      - PORT=50051

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HELLO_SERVICE_ADDR=hello:50051
    depends_on:
      - hello
