apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      annotations:
        io.containerd.cri.runtime-handler: kata-qemu-sev
      labels:
        app: gateway
    spec:
      runtimeClassName: kata-qemu-sev
      containers:
      - name: gateway
        image: tanakaryuki/gateway-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: HELLO_SERVICE_ADDR
          value: "hello:50051"
